- name: kuberlab
  charts:
    - name: demo-web-server
      src: https://github.com/kuberlab/demo-web-server/Chart
      #src: https://dev.kuberlab.io/kuberlab/demo-web-server
      version: "*"
      clusters:
        - master-test
      configuration:
        values:
          Name: demo
          Component: demo-server
          ServerVersion: 1.1.0
          Replicas: 2
          CpuRequests: "25m"
          MemoryRequests: "64Mi"
          CpuLimits: "200m"
          MemoryLimits: "64Mi"
          Image:
            Name: kuberlab/demo-web-server
            Tag: latest
            Current: latest